# Generated by Django 3.0.5 on 2021-01-21 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='student', max_length=50, null=True)),
                ('address', models.EmailField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('cell_number', models.CharField(max_length=20, null=True)),
                ('role', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('ratherNotSay', 'Rather Not Say')], max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
