# Generated by Django 3.1.7 on 2021-05-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_auto_20210524_2312'),
        ('users', '0007_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='levelInt',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.team'),
        ),
    ]
