# Generated by Django 3.0.5 on 2020-12-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('createdAt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNumber', models.CharField(max_length=200, null=True)),
                ('timeStamp', models.CharField(max_length=200, null=True)),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('n', models.CharField(max_length=200, null=True)),
                ('p', models.CharField(max_length=200, null=True)),
                ('k', models.CharField(max_length=200, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.device')),
            ],
        ),
    ]
