# Generated by Django 3.0.5 on 2020-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='createdAt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timeStamp',
            field=models.DateTimeField(null=True),
        ),
    ]
