# Generated by Django 3.0.5 on 2020-12-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201230_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='createdAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
