# Generated by Django 3.0.5 on 2020-12-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20201230_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timeStamp',
            field=models.DateField(null=True),
        ),
    ]
