# Generated by Django 3.0.5 on 2020-12-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20201231_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='timeStamp',
            new_name='date',
        ),
    ]
