# Generated by Django 3.0.5 on 2021-01-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20201231_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
