# Generated by Django 3.0.5 on 2021-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='battery',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
