# Generated by Django 3.0.5 on 2021-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_sensordata_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='soilMoisture',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
