# Generated by Django 3.0.5 on 2021-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_sensordata_soilmoisture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
    ]
