# Generated by Django 3.0.5 on 2021-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_sensordata_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
