# Generated by Django 3.0.5 on 2021-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20210112_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
