# Generated by Django 3.0.5 on 2021-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_sensordata_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='picture',
        ),
        migrations.AddField(
            model_name='device',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
