# Generated by Django 3.0.5 on 2021-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_auto_20210121_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dataFrequency',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
