# Generated by Django 3.0.5 on 2021-01-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_device_datafrequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
    ]
