# Generated by Django 3.1.7 on 2021-03-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_device_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='weatherStationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNumber', models.CharField(max_length=200, null=True)),
                ('timeStamp', models.DateTimeField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('pressure', models.CharField(max_length=20, null=True)),
                ('local_temperature', models.CharField(max_length=20, null=True)),
                ('local_humidity', models.CharField(max_length=20, null=True)),
                ('local_pressure', models.CharField(max_length=20, null=True)),
                ('solar_radiation', models.CharField(max_length=20, null=True)),
                ('sun_rise', models.CharField(max_length=20, null=True)),
                ('sun_set', models.CharField(max_length=20, null=True)),
                ('sun_duration', models.CharField(max_length=20, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('wind_speed', models.CharField(max_length=20, null=True)),
                ('air_quality', models.CharField(max_length=20, null=True)),
                ('battery', models.CharField(max_length=20, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.device')),
            ],
        ),
    ]
