# Generated by Django 3.1.7 on 2021-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_weatherstationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstationdata',
            name='humidity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
