# Generated by Django 3.0.5 on 2021-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_weatherstationdata_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
