# Generated by Django 3.0.5 on 2021-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_auto_20210311_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='weatherstationdata',
            name='device',
        ),
        migrations.DeleteModel(
            name='device',
        ),
        migrations.DeleteModel(
            name='farm',
        ),
        migrations.DeleteModel(
            name='sensorData',
        ),
        migrations.DeleteModel(
            name='weatherStationData',
        ),
    ]
