# Generated by Django 3.0.5 on 2021-03-17 17:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_auto_20210314_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Institute Name')),
                ('weblink', models.URLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('google_pin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell Phone 2')),
            ],
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
