# Generated by Django 3.0.5 on 2021-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_auto_20210317_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='google_pin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='weblink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
