# Generated by Django 3.0.5 on 2021-04-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_auto_20210427_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Team')),
                ('desc', models.TextField(null=True, verbose_name='Description')),
                ('head', models.CharField(max_length=200, null=True, verbose_name='Head')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Company')),
            ],
        ),
    ]
