# Generated by Django 3.0.5 on 2021-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='head',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Head'),
        ),
    ]
