# Generated by Django 3.1.7 on 2021-05-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_auto_20210427_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Team',
            new_name='team',
        ),
    ]
