# Generated by Django 3.1.7 on 2021-05-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_auto_20210524_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('accuracy', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.tasks')),
            ],
        ),
    ]
