# Generated by Django 3.1.7 on 2021-05-31 14:15

import administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_auto_20210525_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='datetime',
            new_name='dateCreation',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=administrator.models.Team, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
