# Generated by Django 3.1.7 on 2021-05-31 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0039_auto_20210531_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Reports',
        ),
    ]
