# Generated by Django 3.2.4 on 2021-06-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0041_auto_20210622_1409'),
    ]

    operations = [
    ]
